### ISSUE TITLE
Github Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by franigam** [matootie/dokube#29]
Github Actions is showing this warning now

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: matootie/dokube@v1.4.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by matootie** [comment]
Thanks for the heads up!

I addressed this in commit d928bf89877df4f5170c2d56cc07a70cbd2c4c8b
It's reflected in version `1.4.1`, please use that instead
The warnings are gone https://github.com/matootie/dokube/actions/runs/7811345794
